### ISSUE TITLE
PlugIn Install Language Problem 

### ISSUE THREAD

**Issue by WeAppU** [wirecard/virtuemart3-wcp#19]
On Joomla Install there is this Error on Install:
JInstaller: :Install: Die Datei „home/blabla/blabla/tmp/install_5b3d07f25c663/en-GB.plg_vmpayment_wirecardceecheckout.ini“ existiert nicht.

**Comment by WeAppU** [comment]
And also the German Language isnt Loading...
But its in the Right Folder:
root/plugins/vmpayment/wirecardceecheckout/language/de-DE

**Comment by rinnhofer** [comment]
Hello,
maybe you can give us more information how to reprodruce your error. In our installation process no error appeared. Which Joomla version and which VirtueMart version are you using?

Kind regards
